global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules"

scrape_configs:
  - job_name: "nodes"
    static_configs:
      - targets: 
          # Add your hosts here, i.e. "192.168.1.10:9100", etc.
          - "localhost:9100"
